Squash: changed mount point to /mnt; check if mount succeeded;

diff --git a/usb b/usb
--- a/usb
+++ b/usb
@@ -1,6 +1,6 @@
 #!/system/bin/sh
 #
-# W.I.P. script, by XDA@USBhost. made for the Nexus 9 in mind.
+# W.I.P. script, by XDA@USBhost. made for the Nexus 9/aarch64 in mind.
 # If your using f2fs i am assuming the kernel is using the latest f2fs.
 #
 
@@ -14,11 +14,11 @@ fi
 
 #globle
 BB="$(find /system -name busybox | head -n 1)"; # BusyBox
-MF="USB";                 # Mount Folder
-MP="/data/media/0/${MF}"; # Mount point
-MFP="/sdcard/${MF}";      # Mount Folder point
+MF="USB"; #-------------------------------------- Mount Folder
+MP="/mnt/${MF}"; #------------------------------- Mount point
 
 function helpd() {
+
 	echo "
 Usage: -m BLOCK FILE-SYSTEM // like -m sda f2fs
 Note: if FILE-SYSTEM is not specified (like -m sda )
@@ -54,6 +54,7 @@ Supported file systems (to repair):
 
 # list mount points
 function listd() {
+
 	for f in /dev/block/sd*; 
 	do 
 		echo "${f##*/}"; 
@@ -62,12 +63,26 @@ function listd() {
 
 # mount
 function mountd() {
-	mkdir -p "${MFP}";
+
+	function mountcheck() 
+	{
+		mountcheck="$("${BB}" mount | "${BB}" grep -o "${MP}")";
+		if [ "${mountcheck}" != "${MP}" ]; then
+			echo "Mount failed";
+			exit 1;
+		elif [ "${mountcheck}" = "${MP}" ]; then
+			echo "Mount success";
+		fi
+	}
+
+	mkdir -p "${MP}";
+	chmod 777 "${MP}";
 	
 	if [ "${3}" != "" ]; then
 		# vfat does not need umask=000 because it has no permission support.
 		if [ "${3}" = "ntfs" ]; then
-			"${BB}" mount -t "${3}" -o rw,umask=000,nls=utf8 /dev/block/"${2}" "${MP}";
+			"${BB}" mount -t "${3}" -o rw,umask=000 /dev/block/"${2}" "${MP}";
+			"${BB}" mount -o remount,nls=utf8,nofail "${MP}"; # if this fails no worrys
 		elif [ "${3}" = "exfat" ]; then
 			"${BB}" mount -t "${3}" -o rw,umask=000 /dev/block/"${2}" "${MP}";
 		else
@@ -76,9 +91,9 @@ function mountd() {
 	else
 		"${BB}" mount -t auto -o rw /dev/block/"${2}" "${MP}";
 	fi
+	mountcheck;
 	
-	echo "Mounted: ${MP}";
-	echo "Access here: ${MFP}";
+	echo "Access here: ${MP}";
 }
 
 # umount
@@ -89,6 +104,7 @@ function umountd() {
 
 # format
 function formatd() {
+
 	f2fs="/system/etc/usblib/mkfs.f2fs";
 	ext="/system/etc/usblib/mke2fs";
 	vfat="/system/etc/usblib/mkfs.fat";
@@ -108,7 +124,7 @@ function formatd() {
 			mountd - "${2}" "${3}";
 			chmod -R 777 "${MP}";
 		elif [ "${3}" = "ntfs" ]; then
-			echo "not supported yet";
+			echo "not supported";
 		elif [ "${3}" = "vfat" ]; then
 			"${vfat}" /dev/block/"${2}";
 			mountd - "${2}" "${3}";
@@ -121,6 +137,7 @@ function formatd() {
 
 # repair
 function repaird() {
+
 	f2fs="/system/etc/usblib/fsck.f2fs";
 	ext="/system/etc/usblib/e2fsck";
 	vfat="/system/etc/usblib/fsck.fat";
